package export

// defaultObsidianTemplate is the default template for Obsidian export.
// It uses Go's text/template syntax with custom functions.
const defaultObsidianTemplate = `---
{{- with .Frontmatter }}
date: {{ .Date }}
project: {{ .Project }}
branch: {{ .Branch }}
commit: {{ .Commit }}
commit_short: {{ .CommitShort }}
{{- if .Author }}
author: {{ .Author }}
{{- end }}
review_mode: {{ .ReviewMode }}
files_reviewed: {{ .FilesReviewed }}
total_issues: {{ .TotalIssues }}
severity:
  critical: {{ .CriticalIssues }}
  error: {{ .ErrorIssues }}
  warning: {{ .WarningIssues }}
  info: {{ .InfoIssues }}
average_score: {{ .AverageScore }}
duration: {{ .Duration }}
tags:
{{- range .Tags }}
  - {{ . }}
{{- end }}
{{- if .Aliases }}
aliases:
{{- range .Aliases }}
  - {{ . }}
{{- end }}
{{- end }}
{{- end }}
---

# Code Review: {{ .Metadata.ProjectName }}

{{- if .Config.IncludeTags }}

{{ formatTags .Frontmatter.Tags }}
{{- end }}

## Summary

| Metric | Value |
|--------|-------|
| Files Reviewed | {{ len .Result.Files }} |
| Total Issues | {{ .Result.TotalIssues }} |
| Duration | {{ .Result.Duration }} |
| Average Score | {{ .Frontmatter.AverageScore }}/100 |

### Issue Breakdown

| Severity | Count |
|----------|-------|
| :red_circle: Critical | {{ .Frontmatter.CriticalIssues }} |
| :orange_circle: Error | {{ .Frontmatter.ErrorIssues }} |
| :yellow_circle: Warning | {{ .Frontmatter.WarningIssues }} |
| :blue_circle: Info | {{ .Frontmatter.InfoIssues }} |

{{- if gt .Result.TotalIssues 0 }}

## Issues

{{- range .Result.Files }}
{{- if and .Response (gt (len .Response.Issues) 0) }}

### ` + "`{{ .File }}`" + `
{{- if .Cached }}
_Cached result_
{{- end }}

{{- range .Response.Issues }}

{{- if $.Config.IncludeCallouts }}

> [!{{ severityCallout .Severity }}] {{ severityIcon .Severity }} **[{{ .Type }}]** {{ .Message }}
{{- if .Location }}
> **Location:** Line {{ .Location.StartLine }}{{ if and .Location.EndLine (gt .Location.EndLine .Location.StartLine) }}-{{ .Location.EndLine }}{{ end }}
{{- end }}
{{- if .Suggestion }}
>
> **Suggestion:** {{ .Suggestion }}
{{- end }}
{{- if .FixedCode }}
>
> **Suggested Fix:**
> ` + "```" + `
> {{ .FixedCode }}
> ` + "```" + `
{{- end }}
{{- if .RootCause }}
>
> **Root Cause:** {{ .RootCause.Description }}
{{- end }}
{{- else }}

#### {{ severityIcon .Severity }} [{{ .Type }}] {{ .Message }}

{{- if .Location }}
**Location:** Line {{ .Location.StartLine }}{{ if and .Location.EndLine (gt .Location.EndLine .Location.StartLine) }}-{{ .Location.EndLine }}{{ end }}
{{- end }}

{{- if .Suggestion }}
**Suggestion:** {{ .Suggestion }}
{{- end }}

{{- if .FixedCode }}
**Suggested Fix:**
` + "```" + `
{{ .FixedCode }}
` + "```" + `
{{- end }}

{{- if .RootCause }}
**Root Cause:** {{ .RootCause.Description }}
{{- end }}
{{- end }}

---
{{- end }}
{{- end }}
{{- end }}
{{- else }}

> [!success] No Issues Found
> All reviewed files passed the code review.

{{- end }}

{{- if and .Config.IncludeLinks (gt (len .RelatedReviews) 0) }}

## Related Reviews

{{- range .RelatedReviews }}
- {{ wikiLink . }}
{{- end }}
{{- end }}

---
*Generated by [GoReview](https://github.com/JNZader/goreview) at {{ formatTime .Metadata.ReviewDate }}*
`
